{"name": "test_one", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 1 == 2", "trace": "self = <Testcases.test_three.TestThree object at 0x000001C1D786FB50>\n\n    @pytest.mark.xfail\n    def test_one(self):\n        logger.info(\"TestThree开始执行\")\n        print(\"测试类的部分前置\")\n        logger.info(\"TestThree执行结束\")\n>       assert 1==2\nE       assert 1 == 2\n\nTestcases\\test_three.py:17: AssertionError"}, "start": 1690882446029, "stop": 1690882446030, "uuid": "77966021-1953-413b-9628-3054677c099f", "historyId": "11259db53a7421ea422434c4d7d35443", "testCaseId": "eeb6dd70abaf098b2bcbc6638b279c39", "fullName": "Testcases.test_three.TestThree#test_one", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "tag", "value": "@pytest.mark.usefixtures('sql_fix')"}, {"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "Testcases"}, {"name": "suite", "value": "test_three"}, {"name": "subSuite", "value": "TestThree"}, {"name": "host", "value": "LAPTOP-KFR5BLTF"}, {"name": "thread", "value": "20848-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcases.test_three"}]}